# KNN알고리즘

## 1. numpy import & DataSet
+ numpy import
+ group&labels로 dataset 생성
    - array는 [] 사용 
    - tuple은 () 사용
    - dict는 {} 사용

In [1]:
from numpy import *
import operator

def createDataSet() :
    group = array([ [1.0, 2.0], [1.0, 4.0], [4.0, 1.0], [4.0,2.0] ])
    labels = ['Action', 'Action', 'Romantic', 'Romantic']
    return group, labels

In [2]:
group, labels = createDataSet()
print(group) 
print(labels)

[[1. 2.]
 [1. 4.]
 [4. 1.]
 [4. 2.]]
['Action', 'Action', 'Romantic', 'Romantic']


In [10]:
from numpy import *
import operator

def createDataSet2() :
    group = array([ [4.0, 1.0], [4.0,2.0], [1.0, 2.0], [1.0, 4.0]])
    labels = ['Action', 'Action', 'Romantic', 'Romantic']
    return group, labels
group, labes = createDataSet2()

# 2. calcDistance
+ inX = [2.0, 3.0]
    + 알고자 하는 X의 위치<br>
<br>
+ dataSet = group
+ labels = labels
+ k = 3
<br><br>

+ dataSetSize = dataSet.shape[0]
    + datasize : dataSet.shape를 이용하여 구함 = 4
        + .shape row의 개수를 반환<br><br>
    
+ sqDiffMat = diffMat ** 2
+ sqDistances = sqDiffMat.sum(axis=1)
+ distances = sqDistances ** 0.5
    + diffMat : tile(inX, (dataSetSize, 1)) - dataSet으로 두 점 사이 거리 벡터
    + sqDiffMat : 피타고라스 이용 $$x^2 + y^2$$
    + distances : root이용 거리 계산
<br><br>

+ sortedDistIndices = distnaces.argsort()
    + 어레이 distnaces를 정렬하는 '인덱스의 어레이'를 반환
    + 즉, 거리순서를 반환

In [11]:
def calcDistance(inX, dataSet, labels, k):
    # shape is a tuple that gives dimensions of the array
    # shape[0] returns the number of rows, here will return 4
    dataSetSize = dataSet.shape[0]
    #dataSetSize = 4
    
    # numpy.tile(A, reps): construct an array by repeating A the number of times given by reps
    # if reps has length d, the result will have dimension of max(d, A.ndim)
    # tile(inX, (dataSetSize,1)) will return [ [0,0] [0,0] [0,0] [0,0] ]
    # diffMat is [ [1, 1], [1, -1], [-2, 2], [-2, 1] ]
    diffMat = tile(inX, (dataSetSize, 1)) - dataSet
    # **2 means square
    sqDiffMat = diffMat ** 2
    
    # sqDistances = x^2 + y^2
    sqDistances = sqDiffMat.sum(axis=1)
    # distance is equal to the square root of the sum of the squares of the coordinates
    # distance = [2, 2, 8, 5]
    distances = sqDistances ** 0.5
    
    # numpy.argsort() returns the indices that would sort an array
    # here returns [0 1 3 2]
    sortedDistIndices = distances.argsort()
    
    return sortedDistIndices

In [12]:
sortedDistIndices = calcDistance([2.0, 3.0], group, labels, 3)
print(sortedDistIndices)

[2 3 1 0]


# 3. findMajorityClass
+ classCount dict 생성
+ 거리가 가까운 순으로 k개 label list 생성
+ 

In [23]:
list = array([7,6,3,4,2,5])
a = list.argsort()
print(list)
print(a)
print(list[a])

[7 6 3 4 2 5]
[4 2 3 5 1 0]
[2 3 4 5 6 7]


In [14]:
def findMajorityClass(inX, dataSet, labels, k, sortedDistIndices):
    classCount = {}

    # iterate k times from the closest item
    for i in range(k):
        voteIlabel = labels[sortedDistIndices[i]]
        print(sortedDistIndices[i], voteIlabel)
        
        # increase +1 on the selected label
        classCount[voteIlabel] = classCount.get(voteIlabel, 0) + 1

    # classCount dictionary : {'Action': 2, 'Romantic': 1}
    # sort ClassCount Descending order

    return sorted(classCount, key=operator.itemgetter(1), reverse=True)

In [15]:
findMajorityClass([2.0, 3.0], group, labels, 3,sortedDistIndices)

2 Romantic
3 Romantic
1 Action


['Romantic', 'Action']

In [16]:
def classify0(inX, dataSet, labels, k):
    # calculate the distance between inX and the current point
    sortedDistIndices = calcDistance(inX, dataSet, labels, k)
    # take k items with lowest distances to inX and find the majority class among k items
    sortedClassCount = findMajorityClass(inX, dataSet, labels, k, sortedDistIndices)
    # sortedClassCount is now [('Action', 2)], therefore return Action
    return sortedClassCount[0]

In [17]:
group, labels = createDataSet()
result = classify0([2.0, 3.0], group, labels, 3)
print (result)

0 Action
1 Action
3 Romantic
Romantic
